### ISSUE TITLE
lost connection: The server is still loading, please, wait a bit and try joining again.

### ISSUE THREAD

**Issue by ruk13xa** [mirrerror/DiscordUtilsRecoded#24]
2|kr_smp  | [22:29:53 WARN]: [DiscordUtils] Plugin DiscordUtils v5.0.1 generated an exception while executing task 53
2|kr_smp  | java.lang.IllegalArgumentException: Name may not be null
2|kr_smp  |     at DiscordUtils.jar/shaded.net.dv8tion.jda.internal.utils.Checks.notNull(Checks.java:83) ~[DiscordUtils.jar:?]
2|kr_smp  |     at DiscordUtils.jar/shaded.net.dv8tion.jda.internal.utils.Checks.notBlank(Checks.java:97) ~[DiscordUtils.jar:?]
2|kr_smp  |     at DiscordUtils.jar/shaded.net.dv8tion.jda.api.entities.Activity.listening(Activity.java:225) ~[DiscordUtils.jar:?]
2|kr_smp  |     at DiscordUtils.jar/shaded.net.dv8tion.jda.api.entities.Activity.of(Activity.java:351) ~[DiscordUtils.jar:?]
2|kr_smp  |     at DiscordUtils.jar/shaded.net.dv8tion.jda.api.entities.Activity.of(Activity.java:315) ~[DiscordUtils.jar:?]
2|kr_smp  |     at DiscordUtils.jar/md.mirrerror.discordutils.discord.Activities.lambda$getActivitiesFromConfig$0(Activities.java:37) ~[DiscordUtils.jar:?]
2|kr_smp  |     at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
2|kr_smp  |     at DiscordUtils.jar/md.mirrerror.discordutils.discord.Activities.getActivitiesFromConfig(Activities.java:33) ~[DiscordUtils.jar:?]
2|kr_smp  |     at DiscordUtils.jar/md.mirrerror.discordutils.discord.Activities.<init>(Activities.java:20) ~[DiscordUtils.jar:?]
2|kr_smp  |     at DiscordUtils.jar/md.mirrerror.discordutils.models.DiscordUtilsBot.setupBot(DiscordUtilsBot.java:189) ~[DiscordUtils.jar:?]
2|kr_smp  |     at DiscordUtils.jar/md.mirrerror.discordutils.Main.lambda$onEnable$1(Main.java:102) ~[DiscordUtils.jar:?]
2|kr_smp  |     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.jar:1.21-2275-82ccc76]
2|kr_smp  |     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.jar:?]
2|kr_smp  |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
2|kr_smp  |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
2|kr_smp  |     at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by ruk13xa** [comment]
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/1ed3c9d3-77a5-473e-9613-2d02339f4c2a">

**Comment by ruk13xa** [comment]
<img width="563" alt="image" src="https://github.com/user-attachments/assets/bbbee1ff-970f-4b25-ace6-1860deb9f481">

**Comment by mirrerror** [comment]
You wrote a wrong activity name. The available ones are written at the top of the bot_settings.yml file.
